export enum MODE {
  NORMAL = "NORMAL_MODE",
  INSERT = "INSERT_MODE",
}

export enum TASK_TYPE {
  DRAFT = "DRAFT_TASK",
  ONGOING = "ONGOING_TASK",
  DRAFT_ONGOING = "DRAFT_ONGOING_TASK",
  FINISHED = "FINISHED_TASK",
}
